# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763f64e24c074edbd0fd67eebb3fd7fc52f49bddf3596832c0ed587f899b2dbbd7370cace3f47d9724dec3d478d102eab2e88bdc65e23ee462e281bdec7125d3

test:
  secret_key_base: 85cff319ff12e13f39ad5158150a48b252931c9d3973c3370ba42c71a8258fd796095dfc094e00ab46e56bf4fa64dcd4bcbdf5ceb76ba8805ecd4c2e5628a2b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
